Repository graasp/graasp-library, pull requests merged in 2023-11, with the labels that each got.

#401 feat: add liked items page
  cypress/e2e/myLists/myFavorites.cy.ts
  cypress/e2e/myLists/myLikes.cy.ts
  package.json
  pages/liked.tsx
  src/components/collection/ChildrenCard.tsx
  src/components/collection/Items.tsx
  src/components/common/Error.tsx
  src/components/layout/HeaderLeftContent.tsx
  src/components/layout/UserSwitchWrapper.tsx
  src/components/pages/MyFavorites.tsx
  src/components/pages/MyLikes.tsx
  src/components/pages/MyList.tsx
  src/config/messages.ts
  src/config/routes.ts
  src/langs/constants.ts
  src/langs/en.json
  yarn.lock
Labels: feature

#415 fix: add clickable tags in collection header
  src/components/collection/summary/SummaryHeader.tsx
  src/components/layout/HomeHeader.tsx
Labels: improvement

#427 chore: upgrade yarn to v4
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.6.3.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: chore

#431 fix: path to analytics items
  src/components/common/HeaderNavigation.tsx
Labels: bug

#434 fix: update docker image
  .yarn/releases/yarn-3.6.4.cjs
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  yarn.lock
Labels: build

#444 fix: update task def for aws prod env
  .aws/graasp-library-prod.json
  .aws/graasp-library-stage.json
  .aws/refactor.json
Labels: build
