Repository graasp/graasp-library, pull requests merged in 2024-07, with the labels that each got.

#633 fix: update deps and release-please
  .github/workflows/release-please.yml
  package.json
  src/components/collection/ChildrenCard.tsx
  src/components/collection/summary/SummaryDetails.tsx
  src/config/i18n.ts
  tsconfig.json
  yarn.lock
Labels: chore

#634 chore(main): release 1.7.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#664 fix: update deps
  .husky/commit-msg
  .husky/post-commit
  .husky/pre-commit
  .husky/pre-push
  package.json
  sentry.client.config.ts
  src/components/collection/DownloadButton.tsx
  yarn.lock
Labels: dependencies
