Repository graasp/graasp-library, pull requests merged in 2024-10, with the labels that each got.

#697 chore(main): release 1.10.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#703 chore(main): release 1.10.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#704 fix: change usage of edit current member hook
  package.json
  src/components/collection/ItemBreadcrumb.tsx
  src/components/layout/Footer.tsx
  yarn.lock
Labels: chore

#711 fix: upgrade mui v6
  .eslintrc
  cypress/support/commands.ts
  cypress/support/cypress.ts
  cypress/support/server.ts
  package.json
  src/components/collection/ChildrenCard.tsx
  src/components/collection/CollectionsGrid.tsx
  src/components/collection/Items.tsx
  src/components/collection/summary/SummaryDetails.tsx
  src/components/layout/Footer.tsx
  yarn.lock
Labels: dependencies

#712 feat: use item lang instead of category lang
  .eslintrc
  cypress/e2e/allCollections/allCollections.cy.ts
  package.json
  src/components/collection/Collection.tsx
  src/components/collection/summary/Summary.tsx
  src/components/collection/summary/SummaryDetails.tsx
  src/components/filters/CategoryFilter.tsx
  src/components/filters/Filter.tsx
  src/components/filters/FilterHeader.tsx
  src/components/filters/FilterPopper.tsx
  src/components/filters/LangFilter.tsx
  src/components/pages/AllCollections.tsx
  src/config/selectors.ts
  src/langs/ar.json
  src/langs/constants.ts
  src/langs/de.json
  src/langs/en.json
  src/langs/es.json
  src/langs/fr.json
  src/langs/it.json
  yarn.lock
Labels: feature
