Repository graasp/graasp-library, pull requests merged in 2024-01, with the labels that each got.

#470 fix: keep search case when navigating
  src/components/common/Wrapper.tsx
  src/components/search/Search.tsx
  src/langs/de.json
  src/langs/en.json
  src/langs/fr.json
Labels: bug, chore

#479 fix: set white background in collection view
  app/collections/[id]/page.tsx
  src/components/common/Wrapper.tsx
  src/components/layout/HomeHeader.tsx
Labels: bug

#487 fix: use test env in cypress open and remove post-merge hook
  .husky/post-merge
  package.json
Labels: build

#508 feat: use `date-fns` instead of `luxon`
  app/all-collections/page.tsx
  app/icon.svg
  app/layout.tsx
  cypress/e2e/myLists/myPublishments.cy.ts
  package.json
  public/defaultAvatar.png
  public/favicon.ico
  public/homePageIcon.png
  public/icon.png
  src/components/collection/ChildrenCard.tsx
  src/components/collection/CopyButton.tsx
  src/components/collection/Items.tsx
  src/components/collection/summary/Summary.tsx
  src/config/constants.ts
  src/utils/date.js
  yarn.lock
Labels: chore, dependencies, improvement
