Repository graasp/graasp-library, pull requests merged in 2025-07, with the labels that each got.

#804 fix: remove br tag in translations
  messages/ar.json
  messages/de.json
  messages/en.json
  messages/es.json
Labels: bug

#802 fix: word break on cards
  src/components/common/Card/BigCard.tsx
  src/components/ui/Card.stories.tsx
  src/components/ui/Card.tsx
Labels: bug

#801 fix: embedded link in collection view
  messages/en.json
  playwright.config.ts
  src/components/collection/summary/SummaryActionButtons.tsx
  src/config/env.ts
  src/config/paths.ts
  tests/flows.spec.ts
Labels: bug

#800 fix: add active link styling on header
  package.json
  src/components/Header.tsx
Labels: improvement

#808 fix: use sort instead of toSorted for compatibility
  src/components/collection/collectionCard/CollectionCard.tsx
Labels: bug

#811 fix(ci): remove tests that are often flacky in safari
  tests/flows.spec.ts
  tests/search.spec.ts
Labels: chore, test

#799 chore(main): release 2.0.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#815 fix: add width 100% to summary section
  src/components/collection/summary/Summary.tsx
Labels: bug, ui :eye:

#817 chore(main): release 2.1.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
